#!/usr/bin/env python3
"""
Build data/bigram.tsv from rime-essay character bigrams.

Extracts consecutive character pairs from all multi-character words,
weighted by word frequency. Filters to pairs with total count >= MIN_COUNT.

Requires build_dict.py to have been run first (uses its essay.txt cache).

Usage:
    python scripts/build_bigram.py [--output data/bigram.tsv] [--min-count 1000]
"""

import argparse
import sys
from collections import defaultdict
from pathlib import Path

CACHE_DIR = Path(__file__).parent / "cache"
ESSAY_CACHE = CACHE_DIR / "essay.txt"

HEADER = """\
# Character bigrams from rime-essay
# Source: https://github.com/rime/rime-essay (Apache 2.0)
# Format: A<TAB>B<TAB>count  (A followed by B, weighted by word frequency)
# Generated by scripts/build_bigram.py — do not edit manually.
"""


def parse_essay(path: Path) -> dict[str, int]:
    words: dict[str, int] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        word = parts[0]
        freq = int(parts[1]) if len(parts) >= 2 and parts[1].isdigit() else 1
        words[word] = freq
    return words


def build_bigrams(essay_words: dict[str, int]) -> dict[tuple[str, str], int]:
    bigrams: dict[tuple[str, str], int] = defaultdict(int)
    for word, freq in essay_words.items():
        if len(word) < 2:
            continue
        for i in range(len(word) - 1):
            bigrams[(word[i], word[i + 1])] += freq
    return bigrams


def main() -> None:
    parser = argparse.ArgumentParser(description="Build Kotori character bigram table")
    parser.add_argument(
        "--output",
        default=str(Path(__file__).parent.parent / "data" / "bigram.tsv"),
    )
    parser.add_argument("--min-count", type=int, default=1000)
    args = parser.parse_args()

    if not ESSAY_CACHE.exists():
        print(
            "ERROR: essay.txt cache not found. Run build_dict.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("parsing essay.txt ...", file=sys.stderr)
    essay_words = parse_essay(ESSAY_CACHE)
    print(f"  {len(essay_words):,} entries", file=sys.stderr)

    print("extracting bigrams ...", file=sys.stderr)
    bigrams = build_bigrams(essay_words)
    print(f"  {len(bigrams):,} unique pairs total", file=sys.stderr)

    filtered = {k: v for k, v in bigrams.items() if v >= args.min_count}
    print(
        f"  {len(filtered):,} pairs with count >= {args.min_count}", file=sys.stderr
    )

    lines = [HEADER.rstrip()]
    for (a, b), count in sorted(filtered.items(), key=lambda x: -x[1]):
        lines.append(f"{a}\t{b}\t{count}")

    Path(args.output).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(filtered):,} entries → {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
