#!/usr/bin/env python3
"""
Build data/pinyin.tsv from RIME terra-pinyin + rime-essay + pypinyin.

Keys are tone-less pinyin (e.g., "ni" for both 你 and 霓).
Frequency disambiguation relies on the Viterbi decoder — more common
characters naturally win when tones are ambiguous.

Requirements: pip install pypinyin
Usage:
    python scripts/build_pinyin_dict.py [--output data/pinyin.tsv]
"""

import argparse
import re
import sys
from pathlib import Path

try:
    from pypinyin import pinyin, Style
except ImportError:
    print("ERROR: pypinyin not installed. Run: pip install pypinyin", file=sys.stderr)
    sys.exit(1)

CACHE_DIR = Path(__file__).parent / "cache"
TERRA_CACHE = CACHE_DIR / "terra_pinyin.dict.yaml"
ESSAY_CACHE = CACHE_DIR / "essay.txt"

HEADER = """\
# 拼音（tone-less） → 繁體中文字典
# Sources:
#   terra_pinyin  (https://github.com/rime/rime-terra-pinyin) Apache 2.0
#   rime-essay    (https://github.com/rime/rime-essay)        Apache 2.0
# Phonetic conversion: pypinyin (MIT)
# Format: pinyin<TAB>word<TAB>frequency  (pinyin has no tone markers)
# Generated by scripts/build_pinyin_dict.py — do not edit manually.
"""


def strip_tone(py: str) -> str:
    """Remove trailing tone digit: 'ni3' → 'ni'."""
    return re.sub(r"[1-5]$", "", py.strip())


# ── Parse terra_pinyin ────────────────────────────────────────────────────────

def parse_terra(data: str) -> dict[str, tuple[str, int]]:
    """Return {char: (best_pinyin_no_tone, weight)} for single-char entries."""
    in_body = False
    chars: dict[str, tuple[str, int]] = {}
    for line in data.splitlines():
        if not in_body:
            if line.strip() == "...":
                in_body = True
            continue
        line = line.rstrip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        word, py_raw = parts[0], parts[1]
        if len(word) != 1:
            continue
        weight_str = parts[2].rstrip("%") if len(parts) >= 3 else "100"
        try:
            weight = int(weight_str)
        except ValueError:
            weight = 1
        existing = chars.get(word)
        if existing is None or weight > existing[1]:
            chars[word] = (strip_tone(py_raw), weight)
    return chars


# ── Parse essay ───────────────────────────────────────────────────────────────

def parse_essay(data: str) -> dict[str, int]:
    words: dict[str, int] = {}
    for line in data.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        word = parts[0]
        freq = int(parts[1]) if len(parts) >= 2 and parts[1].isdigit() else 1
        words[word] = freq
    return words


# ── Pinyin helpers ────────────────────────────────────────────────────────────

def char_to_pinyin(char: str) -> str:
    """Return primary tone-less pinyin for a single character."""
    result = pinyin(char, style=Style.NORMAL, heteronym=False)
    if result and result[0]:
        return strip_tone(result[0][0])
    return ""


def word_to_pinyin(word: str) -> str:
    """Return concatenated tone-less pinyin for a multi-char word."""
    result = pinyin(word, style=Style.NORMAL, heteronym=False)
    parts = []
    for r in result:
        if r:
            parts.append(strip_tone(r[0]))
    return "".join(parts)


# ── Build entries ─────────────────────────────────────────────────────────────

def build_entries(
    char_map: dict[str, tuple[str, int]],
    essay_words: dict[str, int],
) -> list[tuple[str, str, int]]:
    entries: list[tuple[str, str, int]] = []

    # Single characters — use terra_pinyin primary reading; supplement with
    # all pypinyin heteronym readings (at base freq) for full coverage.
    for char, (terra_py, weight) in char_map.items():
        base = max(1, weight * 10)
        essay_freq = essay_words.get(char, 0)
        full_freq = base + essay_freq * 100

        primary_py = terra_py if terra_py else char_to_pinyin(char)
        if not primary_py:
            continue

        # Collect all heteronym readings for this character
        all_py_raw = pinyin(char, style=Style.NORMAL, heteronym=True)
        all_py: list[str] = []
        if all_py_raw and all_py_raw[0]:
            all_py = [strip_tone(p) for p in all_py_raw[0] if p]

        for py in set(all_py):
            if not py:
                continue
            freq = full_freq if py == primary_py else base
            entries.append((py, char, freq))

        if not all_py:
            entries.append((primary_py, char, full_freq))

    # Multi-character compounds from essay (×100 to normalise with single chars)
    for word, freq in essay_words.items():
        if len(word) < 2:
            continue
        try:
            py = word_to_pinyin(word)
        except Exception:
            continue
        if py and py.isascii():
            entries.append((py, word, freq * 100))

    return entries


# ── Output ────────────────────────────────────────────────────────────────────

def write_tsv(entries: list, output_path: str) -> None:
    lines = [HEADER.rstrip()]
    for py, word, freq in sorted(entries, key=lambda e: -e[2]):
        lines.append(f"{py}\t{word}\t{freq}")
    Path(output_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(entries):,} entries → {output_path}", file=sys.stderr)


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Build Kotori Pinyin dictionary")
    parser.add_argument(
        "--output",
        default=str(Path(__file__).parent.parent / "data" / "pinyin.tsv"),
    )
    args = parser.parse_args()

    for cache in (TERRA_CACHE, ESSAY_CACHE):
        if not cache.exists():
            print(
                f"ERROR: {cache.name} not found. Run build_dict.py first.",
                file=sys.stderr,
            )
            sys.exit(1)

    terra_data = TERRA_CACHE.read_text(encoding="utf-8")
    essay_data = ESSAY_CACHE.read_text(encoding="utf-8")

    char_map = parse_terra(terra_data)
    essay_words = parse_essay(essay_data)
    print(
        f"chars: {len(char_map):,}  essay words: {len(essay_words):,}",
        file=sys.stderr,
    )

    entries = build_entries(char_map, essay_words)
    if not entries:
        print("ERROR: no entries generated", file=sys.stderr)
        sys.exit(1)

    write_tsv(entries, args.output)


if __name__ == "__main__":
    main()
