// 拼音輸入分割器 (tone-less greedy longest-match)
// Segments a raw key sequence into Mandarin pinyin syllables (longest-first).
// Apostrophe (xi'an) → skipped; spaces/punctuation → Passthrough; case-insensitive.

// 419 valid Mandarin pinyin syllables (tone-less, longest-first)
// Generated by scripts/_gen_syllables.py from pypinyin over U+4E00..U+9FFF
const VALID_SYLLABLES: &[&str] = &[
    "chuang", "shuang", "zhuang", "chang", "cheng", "chong", "chuai", "chuan", "guang", "huang",
    "jiang", "jiong", "kuang", "liang", "niang", "qiang", "qiong", "shang", "sheng", "shuai",
    "shuan", "xiang", "xiong", "zhang", "zheng", "zhong", "zhuai", "zhuan", "bang", "beng", "bian",
    "biao", "bing", "cang", "ceng", "chai", "chan", "chao", "chen", "chou", "chua", "chui", "chun",
    "chuo", "cong", "cuan", "dang", "deng", "dian", "diao", "ding", "dong", "duan", "fang", "feng",
    "fiao", "gang", "geng", "gong", "guai", "guan", "hang", "heng", "hong", "huai", "huan", "jian",
    "jiao", "jing", "juan", "kang", "keng", "kong", "kuai", "kuan", "lang", "leng", "lian", "liao",
    "ling", "long", "luan", "mang", "meng", "mian", "miao", "ming", "nang", "neng", "nian", "niao",
    "ning", "nong", "nuan", "pang", "peng", "pian", "piao", "ping", "qian", "qiao", "qing", "quan",
    "rang", "reng", "rong", "ruan", "sang", "seng", "shai", "shan", "shao", "shei", "shen", "shou",
    "shua", "shui", "shun", "shuo", "song", "suan", "tang", "teng", "tian", "tiao", "ting", "tong",
    "tuan", "wang", "weng", "xian", "xiao", "xing", "xuan", "yang", "ying", "yong", "yuan", "zang",
    "zeng", "zhai", "zhan", "zhao", "zhei", "zhen", "zhou", "zhua", "zhui", "zhun", "zhuo", "zong",
    "zuan", "ang", "bai", "ban", "bao", "bei", "ben", "bie", "bin", "cai", "can", "cao", "cen",
    "cha", "che", "chi", "chu", "cou", "cui", "cun", "cuo", "dai", "dan", "dao", "dei", "den",
    "dia", "die", "diu", "dou", "dui", "dun", "duo", "eng", "fan", "fei", "fen", "fou", "gai",
    "gan", "gao", "gei", "gen", "gou", "gua", "gui", "gun", "guo", "hai", "han", "hao", "hei",
    "hen", "hng", "hou", "hua", "hui", "hun", "huo", "jia", "jie", "jin", "jiu", "jue", "jun",
    "kai", "kan", "kao", "kei", "ken", "kou", "kua", "kui", "kun", "kuo", "lai", "lan", "lao",
    "lei", "len", "lia", "lie", "lin", "liu", "lou", "lun", "luo", "lve", "mai", "man", "mao",
    "mei", "men", "mie", "min", "miu", "mou", "nai", "nan", "nao", "nei", "nen", "nie", "nin",
    "niu", "nou", "nun", "nuo", "nve", "pai", "pan", "pao", "pei", "pen", "pie", "pin", "pou",
    "qia", "qie", "qin", "qiu", "que", "qun", "ran", "rao", "ren", "rou", "rua", "rui", "run",
    "ruo", "sai", "san", "sao", "sen", "sha", "she", "shi", "shu", "sou", "sui", "sun", "suo",
    "tai", "tan", "tao", "tei", "tie", "tou", "tui", "tun", "tuo", "wai", "wan", "wei", "wen",
    "xia", "xie", "xin", "xiu", "xue", "xun", "yan", "yao", "yin", "you", "yue", "yun", "zai",
    "zan", "zao", "zei", "zen", "zha", "zhe", "zhi", "zhu", "zou", "zui", "zun", "zuo", "ai", "an",
    "ao", "ba", "bi", "bo", "bu", "ca", "ce", "ci", "cu", "da", "de", "di", "du", "ei", "en", "er",
    "fa", "fo", "fu", "ga", "ge", "gu", "ha", "he", "hm", "hu", "ji", "ju", "ka", "ke", "ku", "la",
    "le", "li", "lo", "lu", "lv", "ma", "me", "mi", "mo", "mu", "na", "ne", "ng", "ni", "nu", "nv",
    "ou", "pa", "pi", "po", "pu", "qi", "qu", "re", "ri", "ru", "sa", "se", "si", "su", "ta", "te",
    "ti", "tu", "wa", "wo", "wu", "xi", "xu", "ya", "ye", "yi", "yo", "yu", "za", "ze", "zi", "zu",
    "a", "e", "m", "n", "o",
];

#[derive(Debug, PartialEq)]
pub enum Segment {
    /// A valid tone-less pinyin syllable (already lowercased).
    Syllable(String),
    /// A character that passes through unchanged.
    Passthrough(char),
}

pub fn is_valid_syllable(s: &str) -> bool {
    VALID_SYLLABLES.contains(&s)
}

/// Segment a pinyin key sequence into syllables and passthroughs.
///
/// Input is lowercased before matching. Apostrophes are silently dropped
/// (standard pinyin syllable-onset marker: xi'an → [xi, an]).
pub fn segment(input: &str) -> Vec<Segment> {
    let lower = input.to_lowercase();
    let s = lower.as_str();
    let original: Vec<char> = input.chars().collect();

    let mut result = Vec::new();
    let mut pos = 0; // byte position in `s`
    let mut char_pos = 0; // index into `original` for Passthrough original case

    while pos < s.len() {
        let rest = &s[pos..];

        // Skip apostrophe silently (pinyin syllable separator)
        if rest.starts_with('\'') {
            pos += 1;
            char_pos += 1;
            continue;
        }

        // Try longest-first syllable match (VALID_SYLLABLES is sorted longest-first)
        let mut matched = false;
        for &syl in VALID_SYLLABLES {
            if rest.starts_with(syl) {
                result.push(Segment::Syllable(syl.to_string()));
                pos += syl.len();
                char_pos += syl.chars().count();
                matched = true;
                break;
            }
        }

        if !matched {
            // Passthrough: emit the original character (preserving case/Unicode)
            let ch = original[char_pos];
            result.push(Segment::Passthrough(ch));
            pos += ch.len_utf8();
            char_pos += 1;
        }
    }

    result
}

/// Character-coverage confidence: fraction of input chars covered by valid syllables.
///
/// Preferred over syllable-ratio because it penalises inputs where most characters
/// are passthroughs ("hello world" covers 3/11 chars → 0.27).
pub fn confidence(input: &str) -> f32 {
    let total_chars = input.chars().count();
    if total_chars == 0 {
        return 0.0;
    }
    let segs = segment(input);
    let covered: usize = segs
        .iter()
        .filter_map(|s| {
            if let Segment::Syllable(py) = s {
                Some(py.chars().count())
            } else {
                None
            }
        })
        .sum();
    covered as f32 / total_chars as f32
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_nihao() {
        assert_eq!(
            segment("nihao"),
            vec![
                Segment::Syllable("ni".into()),
                Segment::Syllable("hao".into()),
            ]
        );
    }

    #[test]
    fn test_zhongguo() {
        assert_eq!(
            segment("zhongguo"),
            vec![
                Segment::Syllable("zhong".into()),
                Segment::Syllable("guo".into()),
            ]
        );
    }

    #[test]
    fn test_apostrophe_skipped() {
        // xi'an → [xi, an]
        assert_eq!(
            segment("xi'an"),
            vec![
                Segment::Syllable("xi".into()),
                Segment::Syllable("an".into()),
            ]
        );
    }

    #[test]
    fn test_passthrough_punctuation() {
        let segs = segment("ni,hao");
        assert_eq!(segs[0], Segment::Syllable("ni".into()));
        assert_eq!(segs[1], Segment::Passthrough(','));
        assert_eq!(segs[2], Segment::Syllable("hao".into()));
    }

    #[test]
    fn test_case_insensitive() {
        let a = segment("NiHao");
        let b = segment("nihao");
        assert_eq!(a.len(), b.len());
    }

    #[test]
    fn test_confidence_high() {
        assert!(confidence("nihao") > 0.9);
        assert!(confidence("zhongguo") > 0.9);
    }

    #[test]
    fn test_confidence_english_rejected() {
        // "world" → w (pass) + or (pass) + l (pass) + d (pass): very low
        // "hello" → he (syl) + ll (pass) + o (syl): 3/5 = 0.6 — borderline
        // below 0.7 threshold used by PinyinRule
        assert!(confidence("world") < 0.5);
    }
}
